In [2]:
import pandas as pd

In [163]:
df = pd.read_csv('./result/MYC/Transformer_CNN_BindingDB.txt', delimiter = '\t')

In [164]:
df.columns = [0]

num = df[0].str.split('|').str[1]
num2 = []
for i in num:
    try:
        i = i.strip()
        num2.append(i)
    except:
        num2.append(i)
        continue
df['RANK'] = num2

drug = df[0].str.split('|').str[2]
drug2 = []
for i in drug:
    try:
        i = i.strip()
        drug2.append(i)
    except:
        drug2.append(i)
        continue
df['Drug Name'] = drug2

target = df[0].str.split('|').str[3]
target2 = []
for i in target:
    try:
        i = i.strip()
        target2.append(i)
    except:
        target2.append(i)
        continue
df['Target Name'] = target2

score = df[0].str.split('|').str[4]
score2 = []
for i in score:
    try:
        i = i.strip()
        score2.append(i)
    except:
        score2.append(i)
        continue
df['Binding Score'] = score2

del df[0]

In [165]:
df = df.drop([df.index[0],df.index[1],df.index[6113]])
df

,RANK,Drug Name,Target Name,Binding Score
2,1,"2-[(3R,5R,6S)-5-(3-Chlorophenyl)-6-(4-chloroph...",MYC,0.82
3,2,"[(1S,3S,5Z,7R,8Z,11S,12S,13E,15S,17R,21R,23S,2...",MYC,1.02
4,3,Liothyronine,MYC,1.05
5,4,Mometasone,MYC,1.06
6,5,Tacrolimus,MYC,1.08
...,...,...,...,...
6108,6107,L-Pyroglutamic acid,MYC,1033314.77
6109,6108,Triclosan,MYC,1072974.36
6110,6109,Didox,MYC,1095599.61
6111,6110,Dobutamine,MYC,1350975.34
6112,6111,"N-(2-(3,4-Dichlorophenyl)ethyl)-N-methyl-2-(di...",MYC,1383552.05

In [166]:
df.to_csv('./result/MYC/Transformer_CNN_BindingDB.txt', sep = '\t', index = False)