In [1]:
import pandas as pd

In [2]:
cdk = pd.read_csv('./result/CDK_repurposing.txt', delimiter = '\t')
cdk

      RANK              Drug Name Target Name  Binding Score
0        1                 GW0742         CDK           5.65
1        2            Fulvestrant         CDK           9.51
2        3          Norethindrone         CDK          10.38
3        4              Meropenem         CDK          11.22
4        5          Dexamethasone         CDK          13.01
...    ...                    ...         ...            ...
6106  6107             Dichlorvos         CDK     1665984.86
6107  6108              Erteberel         CDK     1784759.18
6108  6109  3-Hydroxybutyric acid         CDK     1797986.79
6109  6110             Isoflurane         CDK     1811758.39
6110  6111          Robison ester         CDK     1913452.88

[6111 rows x 4 columns]

In [29]:
mtor = pd.read_csv('./result/mTOR_repurposing.txt', delimiter = '\t')
mtor

,RANK,Drug Name,Target Name,Binding Score
0,1,Emodin,mtor,123.84
1,2,"N-(6,8-Difluoro-2-methyl-4-quinolinyl)-N'-[4-(...",mtor,166.82
2,3,"6-Chloro-9-((4-methoxy-3,5-dimethylpyridin-2-y...",mtor,176.07
3,4,Prazosin,mtor,194.19
4,5,"(7R,9S,13S,14R,17R)-17-Ethynyl-17-hydroxy-7,13...",mtor,197.31
...,...,...,...,...
6106,6107,alpha-D-Glucose,mtor,2175683.83
6107,6108,"2,2,2-Tribromoethanol",mtor,2237978.45
6108,6109,Octanoic acid,mtor,2287910.55
6109,6110,Robison ester,mtor,2509079.58
6110,6111,Amitriptyline,mtor,2614552.78

In [31]:
egfr = pd.read_csv('./result/EGFR/egfr_repurposing.txt', delimiter = '\t')
egfr

      RANK              Drug Name Target Name  Binding Score
0        1                 GW0742        EGFR           0.80
1        2            Butofilolol        EGFR           2.71
2        3            Fulvestrant        EGFR           3.08
3        4            Seocalcitol        EGFR           3.51
4        5          Norethindrone        EGFR           3.60
...    ...                    ...         ...            ...
6106  6107             Dichlorvos        EGFR     1529567.68
6107  6108          Robison ester        EGFR     1650922.70
6108  6109  3-Hydroxybutyric acid        EGFR     1652386.82
6109  6110             Isoflurane        EGFR     1661842.06
6110  6111              Erteberel        EGFR     1670295.01

[6111 rows x 4 columns]

In [36]:
(mtor.tail(3000)).to_csv('mtor_tail3000.csv', index = False)

In [37]:
(cdk.tail(3000)).to_csv('cdk.tail3000.csv', index = False)

In [38]:
(egfr.tail(3000)).to_csv('egfr.tail3000.csv', index = False)

In [40]:
(mtor.head(3000)).to_csv('mtor_head3000.csv', index = False)
(cdk.head(3000)).to_csv('cdk.head3000.csv', index = False)
(egfr.head(3000)).to_csv('egfr.head3000.csv', index = False)