In [8]:
# import psycopg2
# import pandas as pd

In [3]:
# conn_string = "host = 'localhost' dbname = 'string' user = 'postgres' password = '9860'"
# conn = psycopg2.connect(conn_string)
# cur = conn.cursor()

In [6]:
# # 전체 열 불러오기
# cur.execute("SELECT * FROM evidence.sets;")
# result = cur.fetchall()
# sets = pd.DataFrame(result)
# sets.columns = [desc[0] for desc in cur.description]
# sets['comment']= sets['comment'].str.strip('Name:')
# sets

,set_id,collection_id,title,comment,url
0,aac00010,kegg_pathways,annotated pathway (KEGG),Glycolysis / Gluconeogenesis,http://www.kegg.jp/kegg-bin/show_pathway?aac00010
1,aac00020,kegg_pathways,annotated pathway (KEGG),Citrate cycle (TCA cycle),http://www.kegg.jp/kegg-bin/show_pathway?aac00020
2,aac00030,kegg_pathways,annotated pathway (KEGG),Pentose phosphate pathway,http://www.kegg.jp/kegg-bin/show_pathway?aac00030
3,aac00040,kegg_pathways,annotated pathway (KEGG),Pentose and glucuronate interconversions,http://www.kegg.jp/kegg-bin/show_pathway?aac00040
4,aac00051,kegg_pathways,annotated pathway (KEGG),Fructose and mannose metabolis,http://www.kegg.jp/kegg-bin/show_pathway?aac00051
...,...,...,...,...,...
3269861,ztr04141,kegg_pathways,annotated pathway (KEGG),Protein processing in endoplasmic reticulu,http://www.kegg.jp/kegg-bin/show_pathway?ztr04141
3269862,ztr04144,kegg_pathways,annotated pathway (KEGG),Endocytosis,http://www.kegg.jp/kegg-bin/show_pathway?ztr04144
3269863,ztr04145,kegg_pathways,annotated pathway (KEGG),Phagoso,http://www.kegg.jp/kegg-bin/show_pathway?ztr04145
3269864,ztr04146,kegg_pathways,annotated pathway (KEGG),Peroxiso,http://www.kegg.jp/kegg-bin/show_pathway?ztr04146
3269865,ztr04933,kegg_pathways,annotated pathway (KEGG),AGE-RAGE signaling pathway in diabetic compli...,http://www.kegg.jp/kegg-bin/show_pathway?ztr04933

In [8]:
# # 전체 열 불러오기
# cur.execute("SELECT set_id, item_id, species_id, preferred_name, set_type FROM evidence.sets_items;")
# result = cur.fetchall()
# sets_itmes = pd.DataFrame(result)
# sets_itmes.columns = [desc[0] for desc in cur.description]
# sets_itmes

             set_id  item_id  species_id preferred_name set_type
0          BCRT1000  4432734        9606           CPB2        d
1          BCRT1000  4438421        9606             F2        d
2          BCRT1000  4439430        9606            F2R        d
3          BCRT1001  4433442        9606        ARHGDIB        d
4          BCRT1001  4438651        9606          CASP3        d
...             ...      ...         ...            ...      ...
6370956  wwpdb:6EZO  4448821        9606         EIF2B1        e
6370957  wwpdb:6G79  4435094        9606          GNAO1        e
6370958  wwpdb:6G79  4440566        9606           GNG2        e
6370959  wwpdb:6G79  4443429        9606          HTR1B        e
6370960  wwpdb:6G79  4451621        9606           GNB1        e

[6370961 rows x 5 columns]

In [7]:
# # 필요한 열만 불러오기
# cur.execute("SELECT set_id, collection_id, comment FROM evidence.sets;")
# result = cur.fetchall()
# sets = pd.DataFrame(result)
# sets.columns = [desc[0] for desc in cur.description]
# sets['comment']= sets['comment'].str.strip('Name:')
# sets

,set_id,collection_id,comment
0,aac00010,kegg_pathways,Glycolysis / Gluconeogenesis
1,aac00020,kegg_pathways,Citrate cycle (TCA cycle)
2,aac00030,kegg_pathways,Pentose phosphate pathway
3,aac00040,kegg_pathways,Pentose and glucuronate interconversions
4,aac00051,kegg_pathways,Fructose and mannose metabolis
...,...,...,...
3269861,ztr04141,kegg_pathways,Protein processing in endoplasmic reticulu
3269862,ztr04144,kegg_pathways,Endocytosis
3269863,ztr04145,kegg_pathways,Phagoso
3269864,ztr04146,kegg_pathways,Peroxiso
3269865,ztr04933,kegg_pathways,AGE-RAGE signaling pathway in diabetic compli...

In [9]:
# # 필요한 열만 불러오기
# cur.execute("SELECT set_id, item_id, preferred_name FROM evidence.sets_items;")
# result = cur.fetchall()
# sets_itmes = pd.DataFrame(result)
# sets_itmes.columns = [desc[0] for desc in cur.description]
# sets_itmes

             set_id  item_id preferred_name
0          BCRT1000  4432734           CPB2
1          BCRT1000  4438421             F2
2          BCRT1000  4439430            F2R
3          BCRT1001  4433442        ARHGDIB
4          BCRT1001  4438651          CASP3
...             ...      ...            ...
6370956  wwpdb:6EZO  4448821         EIF2B1
6370957  wwpdb:6G79  4435094          GNAO1
6370958  wwpdb:6G79  4440566           GNG2
6370959  wwpdb:6G79  4443429          HTR1B
6370960  wwpdb:6G79  4451621           GNB1

[6370961 rows x 3 columns]

In [2]:
import pandas as pd
import numpy as np

Pathway 출처 데이터 1

In [3]:
sets = pd.read_csv("sets.csv")
sets

,set_id,collection_id,title,comment,url
0,aac00010,kegg_pathways,annotated pathway (KEGG),Name: Glycolysis / Gluconeogenesis,http://www.kegg.jp/kegg-bin/show_pathway?aac00010
1,aac00020,kegg_pathways,annotated pathway (KEGG),Name: Citrate cycle (TCA cycle),http://www.kegg.jp/kegg-bin/show_pathway?aac00020
2,aac00030,kegg_pathways,annotated pathway (KEGG),Name: Pentose phosphate pathway,http://www.kegg.jp/kegg-bin/show_pathway?aac00030
3,aac00040,kegg_pathways,annotated pathway (KEGG),Name: Pentose and glucuronate interconversions,http://www.kegg.jp/kegg-bin/show_pathway?aac00040
4,aac00051,kegg_pathways,annotated pathway (KEGG),Name: Fructose and mannose metabolism,http://www.kegg.jp/kegg-bin/show_pathway?aac00051
...,...,...,...,...,...
3269861,ztr04141,kegg_pathways,annotated pathway (KEGG),Name: Protein processing in endoplasmic reticulum,http://www.kegg.jp/kegg-bin/show_pathway?ztr04141
3269862,ztr04144,kegg_pathways,annotated pathway (KEGG),Name: Endocytosis,http://www.kegg.jp/kegg-bin/show_pathway?ztr04144
3269863,ztr04145,kegg_pathways,annotated pathway (KEGG),Name: Phagosome,http://www.kegg.jp/kegg-bin/show_pathway?ztr04145
3269864,ztr04146,kegg_pathways,annotated pathway (KEGG),Name: Peroxisome,http://www.kegg.jp/kegg-bin/show_pathway?ztr04146
3269865,ztr04933,kegg_pathways,annotated pathway (KEGG),Name: AGE-RAGE signaling pathway in diabetic c...,http://www.kegg.jp/kegg-bin/show_pathway?ztr04933

In [4]:
sets['collection_id'].unique()

array(['kegg_pathways', 'grid', 'biocarta', 'brenda', 'cell_ontology',
       'biocyc', 'dip', 'hprd', 'efo', 'emdb', 'flannotator',
       'gene_ontology', 'intact', 'interpro', 'mint', 'pid', 'mpidb',
       'reactome', 'pride', 'omim', 'pdbe', 'pmc', 'proteomexchange',
       'rcsb_pdb', 'ww_pdb'], dtype=object)

Pathway 출처 데이터베이스2

In [5]:
sets_items = pd.read_csv("sets_items.csv")
sets_items

             set_id  item_id  species_id preferred_name set_type
0          BCRT1000  4432734        9606           CPB2        d
1          BCRT1000  4438421        9606             F2        d
2          BCRT1000  4439430        9606            F2R        d
3          BCRT1001  4433442        9606        ARHGDIB        d
4          BCRT1001  4438651        9606          CASP3        d
...             ...      ...         ...            ...      ...
6370956  wwpdb:6EZO  4448821        9606         EIF2B1        e
6370957  wwpdb:6G79  4435094        9606          GNAO1        e
6370958  wwpdb:6G79  4440566        9606           GNG2        e
6370959  wwpdb:6G79  4443429        9606          HTR1B        e
6370960  wwpdb:6G79  4451621        9606           GNB1        e

[6370961 rows x 5 columns]

Pathway 출처 데이터베이스에서 homo sapiens 데이터만 빼오기

In [6]:
sets_items_human = sets_items[sets_items['species_id'] == np.int(9606)]
sets_items_human

             set_id  item_id  species_id preferred_name set_type
0          BCRT1000  4432734        9606           CPB2        d
1          BCRT1000  4438421        9606             F2        d
2          BCRT1000  4439430        9606            F2R        d
3          BCRT1001  4433442        9606        ARHGDIB        d
4          BCRT1001  4438651        9606          CASP3        d
...             ...      ...         ...            ...      ...
6370956  wwpdb:6EZO  4448821        9606         EIF2B1        e
6370957  wwpdb:6G79  4435094        9606          GNAO1        e
6370958  wwpdb:6G79  4440566        9606           GNG2        e
6370959  wwpdb:6G79  4443429        9606          HTR1B        e
6370960  wwpdb:6G79  4451621        9606           GNB1        e

[1993252 rows x 5 columns]

Protein-Protein interaction 데이터 (activation/inhibition)

In [7]:
actions = pd.read_csv('actions_all.csv')
actions

,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score
0,6397,7812,activation,activation,f,f,167
1,6404,8012,activation,activation,t,f,429
2,6404,6436,expression,inhibition,t,f,534
3,6404,6436,activation,activation,t,f,150
4,6404,11197,expression,inhibition,t,f,491
...,...,...,...,...,...,...,...
168324682,29519129,29517941,activation,activation,f,f,524
168324683,29519134,29518776,activation,activation,f,f,154
168324684,29519137,29516714,activation,activation,f,f,169
168324685,29519137,29516988,activation,activation,f,f,244
168324686,29519137,29517941,activation,activation,f,f,524

Merge - Pathway 출처 데이터베이스끼리 merge

In [8]:
merge_human_sets = pd.merge(sets_items_human, sets, left_on = 'set_id', right_on = 'set_id')
merge_human_sets

,set_id,item_id,species_id,preferred_name,set_type,collection_id,title,comment,url
0,BCRT1000,4432734,9606,CPB2,d,biocarta,curated pathway,Control,http://pid.nci.nih.gov/search/interaction_land...
1,BCRT1000,4438421,9606,F2,d,biocarta,curated pathway,Control,http://pid.nci.nih.gov/search/interaction_land...
2,BCRT1000,4439430,9606,F2R,d,biocarta,curated pathway,Control,http://pid.nci.nih.gov/search/interaction_land...
3,BCRT1001,4433442,9606,ARHGDIB,d,biocarta,curated pathway,Control,http://pid.nci.nih.gov/search/interaction_land...
4,BCRT1001,4438651,9606,CASP3,d,biocarta,curated pathway,Control,http://pid.nci.nih.gov/search/interaction_land...
...,...,...,...,...,...,...,...,...,...
1993247,wwpdb:6EZO,4448821,9606,EIF2B1,e,ww_pdb,protein-protein interaction,"Detected by psi-mi:""MI:0410""(electron tomograp...",-
1993248,wwpdb:6G79,4435094,9606,GNAO1,e,ww_pdb,protein-protein interaction,"Detected by psi-mi:""MI:0410""(electron tomograp...",-
1993249,wwpdb:6G79,4440566,9606,GNG2,e,ww_pdb,protein-protein interaction,"Detected by psi-mi:""MI:0410""(electron tomograp...",-
1993250,wwpdb:6G79,4443429,9606,HTR1B,e,ww_pdb,protein-protein interaction,"Detected by psi-mi:""MI:0410""(electron tomograp...",-
1993251,wwpdb:6G79,4451621,9606,GNB1,e,ww_pdb,protein-protein interaction,"Detected by psi-mi:""MI:0410""(electron tomograp...",-

In [35]:
merge_human_sets['species_id'].value_counts()

9606    1993252
Name: species_id, dtype: int64

In [9]:
comment = merge_human_sets[['set_id', 'item_id', 'preferred_name', 'comment', 'collection_id', 'title']]
comment

,set_id,item_id,preferred_name,comment,collection_id,title
0,BCRT1000,4432734,CPB2,Control,biocarta,curated pathway
1,BCRT1000,4438421,F2,Control,biocarta,curated pathway
2,BCRT1000,4439430,F2R,Control,biocarta,curated pathway
3,BCRT1001,4433442,ARHGDIB,Control,biocarta,curated pathway
4,BCRT1001,4438651,CASP3,Control,biocarta,curated pathway
...,...,...,...,...,...,...
1993247,wwpdb:6EZO,4448821,EIF2B1,"Detected by psi-mi:""MI:0410""(electron tomograp...",ww_pdb,protein-protein interaction
1993248,wwpdb:6G79,4435094,GNAO1,"Detected by psi-mi:""MI:0410""(electron tomograp...",ww_pdb,protein-protein interaction
1993249,wwpdb:6G79,4440566,GNG2,"Detected by psi-mi:""MI:0410""(electron tomograp...",ww_pdb,protein-protein interaction
1993250,wwpdb:6G79,4443429,HTR1B,"Detected by psi-mi:""MI:0410""(electron tomograp...",ww_pdb,protein-protein interaction
1993251,wwpdb:6G79,4451621,GNB1,"Detected by psi-mi:""MI:0410""(electron tomograp...",ww_pdb,protein-protein interaction

In [74]:
comment['item_id'].value_counts()

4435880    5522
4449992    3972
4436186    3793
4434997    3437
4448814    3288
           ...
4437370       1
4451058       1
4451053       1
4435685       1
4442454       1
Name: item_id, Length: 17972, dtype: int64

Protein name annotation 데이터

In [10]:
proteins = pd.read_csv('proteins.csv')
proteins

,protein_id,protein_external_id,species_id,protein_checksum,protein_size,annotation,preferred_name,annotation_word_vectors
0,6396,287.DR97_1,287,3F1CBDFB4825E37B,749,annotation not available,DR97_1,'annot':1 'avail':3
1,6397,287.DR97_10,287,9160D8F770B8D82C,758,annotation not available,DR97_10,'annot':1 'avail':3
2,6398,287.DR97_100,287,16865CD25374A368,402,annotation not available,nasS,'annot':1 'avail':3
3,6399,287.DR97_1000,287,E49DD64DAC50927B,63,annotation not available,DR97_1000,'annot':1 'avail':3
4,6400,287.DR97_1001,287,22927E3D89CBA08C,442,annotation not available,DR97_1001,'annot':1 'avail':3
...,...,...,...,...,...,...,...,...
24584623,29519136,1577887.JSYG01000072_gene3170,1577887,133E55AD5C8C9A0C,311,annotation not available,JSYG01000072_gene3170,'annot':1 'avail':3
24584624,29519137,1577887.JSYG01000073_gene3165,1577887,05ED53A6C28BF84E,188,annotation not available,JSYG01000073_gene3165,'annot':1 'avail':3
24584625,29519138,1577887.JSYG01000074_gene2341,1577887,5D3F101CA29A169F,141,annotation not available,JSYG01000074_gene2341,'annot':1 'avail':3
24584626,29519139,1577887.JSYG01000075_gene2258,1577887,A80E68CCF514DCDF,78,annotation not available,JSYG01000075_gene2258,'annot':1 'avail':3
24584627,29519140,1577887.JSYG01000076_gene2257,1577887,A47B5DDE3D630372,263,annotation not available,JSYG01000076_gene2257,'annot':1 'avail':3

Protein name 데이터 - homo sapiens 데이터만 저장

In [11]:
proteins_human = proteins[proteins['species_id']==np.int(9606)]
proteins_human

,protein_id,protein_external_id,species_id,protein_checksum,protein_size,annotation,preferred_name,annotation_word_vectors
3771389,4432544,9606.ENSP00000000233,9606,25EF3D4895408147,180,ADP-ribosylation factor 5; GTP-binding protein...,ARF5,"'5':5 'activ':15 'adp':2,23 'adp-ribosyl':1 'a..."
3771390,4432545,9606.ENSP00000000412,9606,1093FE25DEB6C8E8,277,Cation-dependent mannose-6-phosphate receptor;...,M6PR,"'-6':5,32 'acid':50 'apparatus':38 'bear':25 '..."
3771391,4432546,9606.ENSP00000001008,9606,6A498105418D9435,459,Peptidyl-prolyl cis-trans isomerase FKBP4; Imm...,FKBP4,"'90':30 'abil':76 'act':65 'activ':17,54 'also..."
3771392,4432547,9606.ENSP00000001146,9606,A06D1D9944E6726F,512,Cytochrome P450 26B1; Involved in the metaboli...,CYP26B1,"'13':49 '18':69 '26b1':3 '4':60,64 '9':45 'aci..."
3771393,4432548,9606.ENSP00000002125,9606,9F3D667CCE470623,441,"Protein arginine methyltransferase NDUFAF7, mi...",NDUFAF7,"'-118':29 'act':22 'arg':28 'arginin':2,6 'ass..."
...,...,...,...,...,...,...,...,...
3791139,4452105,9606.ENSP00000485671,9606,0D0F20240CEF773E,120,HCG1991042,ENSG00000280273,'hcg1991042':1
3791140,4452106,9606.ENSP00000485672,9606,BAE9E9465D04CBBC,86,annotation not available,ENSG00000279458,'annot':1 'avail':3
3791141,4452107,9606.ENSP00000485673,9606,C1AAD5E15B27AF4A,243,annotation not available,ENSG00000279988,'annot':1 'avail':3
3791142,4452108,9606.ENSP00000485675,9606,74F25F932D19BE12,84,annotation not available,ENSG00000280116,'annot':1 'avail':3
3791143,4452109,9606.ENSP00000485678,9606,1312FAA42BC80E58,317,Olfactory receptor 6Q1; Odorant receptor; Olfa...,OR6Q1,'6':9 '6q1':3 'famili':8 'odor':4 'olfactori':...

In [12]:
names = proteins_human[['protein_id','preferred_name']]
names

         protein_id   preferred_name
3771389     4432544             ARF5
3771390     4432545             M6PR
3771391     4432546            FKBP4
3771392     4432547          CYP26B1
3771393     4432548          NDUFAF7
...             ...              ...
3791139     4452105  ENSG00000280273
3791140     4452106  ENSG00000279458
3791141     4452107  ENSG00000279988
3791142     4452108  ENSG00000280116
3791143     4452109            OR6Q1

[19566 rows x 2 columns]

Protein 파일로 actions(protein-protein interaction)데이터 프로틴 이름 annotation

In [13]:
a = pd.merge(names, actions, left_on = 'protein_id', right_on = 'item_id_a', how = 'left')
a

,protein_id,preferred_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score
0,4432544,ARF5,4432544.0,4434071.0,activation,activation,f,f,309.0
1,4432544,ARF5,4432544.0,4435193.0,activation,activation,f,f,224.0
2,4432544,ARF5,4432544.0,4437287.0,activation,activation,f,f,155.0
3,4432544,ARF5,4432544.0,4437287.0,inhibition,inhibition,f,f,155.0
4,4432544,ARF5,4432544.0,4437360.0,activation,activation,f,f,242.0
...,...,...,...,...,...,...,...,...,...
250648,4452109,OR6Q1,4452109.0,4445657.0,activation,activation,f,f,600.0
250649,4452109,OR6Q1,4452109.0,4448286.0,inhibition,inhibition,f,f,600.0
250650,4452109,OR6Q1,4452109.0,4448521.0,inhibition,inhibition,f,f,600.0
250651,4452109,OR6Q1,4452109.0,4449862.0,activation,activation,t,f,900.0
250652,4452109,OR6Q1,4452109.0,4451621.0,activation,activation,f,f,600.0

In [14]:
a.columns = ['protein_id', 'a_name', 'item_id_a', 'item_id_b', 'mode', 'action', 'is_directional', 'a_is_acting', 'score']
del a['protein_id']
a

,a_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score
0,ARF5,4432544.0,4434071.0,activation,activation,f,f,309.0
1,ARF5,4432544.0,4435193.0,activation,activation,f,f,224.0
2,ARF5,4432544.0,4437287.0,activation,activation,f,f,155.0
3,ARF5,4432544.0,4437287.0,inhibition,inhibition,f,f,155.0
4,ARF5,4432544.0,4437360.0,activation,activation,f,f,242.0
...,...,...,...,...,...,...,...,...
250648,OR6Q1,4452109.0,4445657.0,activation,activation,f,f,600.0
250649,OR6Q1,4452109.0,4448286.0,inhibition,inhibition,f,f,600.0
250650,OR6Q1,4452109.0,4448521.0,inhibition,inhibition,f,f,600.0
250651,OR6Q1,4452109.0,4449862.0,activation,activation,t,f,900.0
250652,OR6Q1,4452109.0,4451621.0,activation,activation,f,f,600.0

In [15]:
b = pd.merge(names, a, left_on = 'protein_id', right_on = 'item_id_b')
b

,protein_id,preferred_name,a_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score
0,4432544,ARF5,CYTH4,4434071.0,4432544.0,activation,activation,f,f,309.0
1,4432544,ARF5,PLD2,4435193.0,4432544.0,activation,activation,f,f,224.0
2,4432544,ARF5,MST1R,4437287.0,4432544.0,activation,activation,f,f,155.0
3,4432544,ARF5,MST1R,4437287.0,4432544.0,inhibition,inhibition,f,f,155.0
4,4432544,ARF5,CYTH3,4437360.0,4432544.0,activation,activation,f,f,242.0
...,...,...,...,...,...,...,...,...,...,...
240331,4452109,OR6Q1,GNG7,4445657.0,4452109.0,activation,activation,f,f,600.0
240332,4452109,OR6Q1,ARRB2,4448286.0,4452109.0,inhibition,inhibition,f,f,600.0
240333,4452109,OR6Q1,ARRB1,4448521.0,4452109.0,inhibition,inhibition,f,f,600.0
240334,4452109,OR6Q1,REEP1,4449862.0,4452109.0,activation,activation,t,t,900.0
240335,4452109,OR6Q1,GNB1,4451621.0,4452109.0,activation,activation,f,f,600.0

In [16]:
b.columns = ['protein_id', 'b_name', 'a_name', 'item_id_a', 'item_id_b', 'mode', 'action', 'is_directional', 'a_is_acting', 'score']
del b['protein_id']
b

,b_name,a_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score
0,ARF5,CYTH4,4434071.0,4432544.0,activation,activation,f,f,309.0
1,ARF5,PLD2,4435193.0,4432544.0,activation,activation,f,f,224.0
2,ARF5,MST1R,4437287.0,4432544.0,activation,activation,f,f,155.0
3,ARF5,MST1R,4437287.0,4432544.0,inhibition,inhibition,f,f,155.0
4,ARF5,CYTH3,4437360.0,4432544.0,activation,activation,f,f,242.0
...,...,...,...,...,...,...,...,...,...
240331,OR6Q1,GNG7,4445657.0,4452109.0,activation,activation,f,f,600.0
240332,OR6Q1,ARRB2,4448286.0,4452109.0,inhibition,inhibition,f,f,600.0
240333,OR6Q1,ARRB1,4448521.0,4452109.0,inhibition,inhibition,f,f,600.0
240334,OR6Q1,REEP1,4449862.0,4452109.0,activation,activation,t,t,900.0
240335,OR6Q1,GNB1,4451621.0,4452109.0,activation,activation,f,f,600.0

In [17]:
b = b.reindex(columns = ['a_name', 'b_name', 'item_id_a', 'item_id_b', 'mode', 'action', 'is_directional', 'a_is_acting', 'score'])
b

,a_name,b_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score
0,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0
1,PLD2,ARF5,4435193.0,4432544.0,activation,activation,f,f,224.0
2,MST1R,ARF5,4437287.0,4432544.0,activation,activation,f,f,155.0
3,MST1R,ARF5,4437287.0,4432544.0,inhibition,inhibition,f,f,155.0
4,CYTH3,ARF5,4437360.0,4432544.0,activation,activation,f,f,242.0
...,...,...,...,...,...,...,...,...,...
240331,GNG7,OR6Q1,4445657.0,4452109.0,activation,activation,f,f,600.0
240332,ARRB2,OR6Q1,4448286.0,4452109.0,inhibition,inhibition,f,f,600.0
240333,ARRB1,OR6Q1,4448521.0,4452109.0,inhibition,inhibition,f,f,600.0
240334,REEP1,OR6Q1,4449862.0,4452109.0,activation,activation,t,t,900.0
240335,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,600.0

In [18]:
b.to_csv('actions_annotation.csv', index = False)

Pathway 출처 데이터베이스와 protein-protein actions 데이터 merge

In [36]:
c = pd.merge(b, comment, left_on = 'a_name', right_on = 'preferred_name')
c

,a_name,b_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score,set_id,item_id,preferred_name,comment,collection_id,title
0,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,BCRT1209,4434071,CYTH4,Control,biocarta,curated pathway
1,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,BCRT325,4434071,CYTH4,Control,biocarta,curated pathway
2,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,BCRT805,4434071,CYTH4,Control,biocarta,curated pathway
3,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:1045222,4434071,CYTH4,"Detected by psi-mi:""MI:0018""(two hybrid) assay",grid,protein-protein interaction
4,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:255681,4434071,CYTH4,"Detected by psi-mi:""MI:0018""(two hybrid) assay",grid,protein-protein interaction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69138775,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,802.0,imex:IM-24272-470,4434436,RFXAP,"Detected by psi-mi:""MI:0007""(anti tag coimmuno...",intact,protein-protein interaction
69138776,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,802.0,imex:IM-26301-171,4434436,RFXAP,"Detected by psi-mi:""MI:1314""(proximity-depende...",intact,protein-protein interaction
69138777,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,802.0,intact:EBI-11060821,4434436,RFXAP,"Detected by psi-mi:""MI:0007""(anti tag coimmuno...",intact,protein-protein interaction
69138778,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,802.0,intact:EBI-16793336,4434436,RFXAP,"Detected by psi-mi:""MI:0007""(anti tag coimmuno...",intact,protein-protein interaction
69138779,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,802.0,intact:EBI-3929303,4434436,RFXAP,"Detected by psi-mi:""MI:0018""(two hybrid) assay",intact,protein-protein interaction

In [38]:
c = c[['a_name', 'b_name', 'item_id_a', 'item_id_b', 'mode', 'action',
       'is_directional', 'a_is_acting', 'set_id', 'score','comment', 'collection_id', 'title']]
c.columns = ['a_name', 'b_name', 'item_id_a', 'item_id_b', 'mode', 'action',
       'is_directional', 'a_is_acting', 'set_id_a', 'score','comment_a', 'collection_id_a', 'title_a']
c

,a_name,b_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,set_id_a,score,comment_a,collection_id_a,title_a
0,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,BCRT1209,309.0,Control,biocarta,curated pathway
1,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,BCRT325,309.0,Control,biocarta,curated pathway
2,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,BCRT805,309.0,Control,biocarta,curated pathway
3,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:1045222,309.0,"Detected by psi-mi:""MI:0018""(two hybrid) assay",grid,protein-protein interaction
4,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:255681,309.0,"Detected by psi-mi:""MI:0018""(two hybrid) assay",grid,protein-protein interaction
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69138775,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,imex:IM-24272-470,802.0,"Detected by psi-mi:""MI:0007""(anti tag coimmuno...",intact,protein-protein interaction
69138776,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,imex:IM-26301-171,802.0,"Detected by psi-mi:""MI:1314""(proximity-depende...",intact,protein-protein interaction
69138777,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,intact:EBI-11060821,802.0,"Detected by psi-mi:""MI:0007""(anti tag coimmuno...",intact,protein-protein interaction
69138778,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,intact:EBI-16793336,802.0,"Detected by psi-mi:""MI:0007""(anti tag coimmuno...",intact,protein-protein interaction
69138779,RFXAP,CIITA,4434436.0,4451905.0,activation,activation,f,f,intact:EBI-3929303,802.0,"Detected by psi-mi:""MI:0018""(two hybrid) assay",intact,protein-protein interaction

In [41]:
c.to_csv('actions_join_a.csv', index = 'False')

In [39]:
d = pd.merge(b, comment, left_on = 'b_name', right_on = 'preferred_name')
d

,a_name,b_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,score,set_id,item_id,preferred_name,comment,collection_id,title
0,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:1032904,4432544,ARF5,"Detected by psi-mi:""MI:0096""(pull down) assay",grid,protein-protein interaction
1,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:1067021,4432544,ARF5,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
2,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:1177364,4432544,ARF5,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
3,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:1178278,4432544,ARF5,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
4,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,309.0,biogrid:1181500,4432544,ARF5,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69138775,REEP1,OR6Q1,4449862.0,4452109.0,activation,activation,t,t,900.0,RCTM163675,4452109,OR6Q1,Control,reactome,curated pathway
69138776,REEP1,OR6Q1,4449862.0,4452109.0,activation,activation,t,t,900.0,RCTM165564,4452109,OR6Q1,Complex: Olfactory receptor:G protein trimer,reactome,curated pathway
69138777,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,600.0,RCTM163674,4452109,OR6Q1,Control,reactome,curated pathway
69138778,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,600.0,RCTM163675,4452109,OR6Q1,Control,reactome,curated pathway
69138779,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,600.0,RCTM165564,4452109,OR6Q1,Complex: Olfactory receptor:G protein trimer,reactome,curated pathway

In [40]:
d = d[['a_name', 'b_name', 'item_id_a', 'item_id_b', 'mode', 'action',
       'is_directional', 'a_is_acting', 'set_id', 'score','comment', 'collection_id', 'title']]
d.columns = ['a_name', 'b_name', 'item_id_a', 'item_id_b', 'mode', 'action',
       'is_directional', 'a_is_acting', 'set_id_b', 'score','comment_b', 'collection_id_b', 'title_b']
d

,a_name,b_name,item_id_a,item_id_b,mode,action,is_directional,a_is_acting,set_id_b,score,comment_b,collection_id_b,title_b
0,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:1032904,309.0,"Detected by psi-mi:""MI:0096""(pull down) assay",grid,protein-protein interaction
1,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:1067021,309.0,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
2,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:1177364,309.0,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
3,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:1178278,309.0,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
4,CYTH4,ARF5,4434071.0,4432544.0,activation,activation,f,f,biogrid:1181500,309.0,"Detected by psi-mi:""MI:0004""(affinity chromato...",grid,protein-protein interaction
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69138775,REEP1,OR6Q1,4449862.0,4452109.0,activation,activation,t,t,RCTM163675,900.0,Control,reactome,curated pathway
69138776,REEP1,OR6Q1,4449862.0,4452109.0,activation,activation,t,t,RCTM165564,900.0,Complex: Olfactory receptor:G protein trimer,reactome,curated pathway
69138777,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,RCTM163674,600.0,Control,reactome,curated pathway
69138778,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,RCTM163675,600.0,Control,reactome,curated pathway
69138779,GNB1,OR6Q1,4451621.0,4452109.0,activation,activation,f,f,RCTM165564,600.0,Complex: Olfactory receptor:G protein trimer,reactome,curated pathway

In [42]:
d.to_csv('actions_join_b.csv', index = 'False')